//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byatikram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ByatikramDBEntities : DbContext
    {
        public ByatikramDBEntities()
            : base("name=ByatikramDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MoneyCollection> MoneyCollections { get; set; }
    
        public virtual ObjectResult<GetPaymentReport_Result> GetPaymentReport(string rollNumber, string paymentMonth)
        {
            var rollNumberParameter = rollNumber != null ?
                new ObjectParameter("RollNumber", rollNumber) :
                new ObjectParameter("RollNumber", typeof(string));
    
            var paymentMonthParameter = paymentMonth != null ?
                new ObjectParameter("PaymentMonth", paymentMonth) :
                new ObjectParameter("PaymentMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentReport_Result>("GetPaymentReport", rollNumberParameter, paymentMonthParameter);
        }
    }
}
