//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byatikram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MoneyCollection> MoneyCollections { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<StudentDue> StudentDues { get; set; }
        public virtual DbSet<StudentRegistration> StudentRegistrations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual ObjectResult<GetPaymentReport_Result> GetPaymentReport(Nullable<int> rollNumber, string paymentMonth)
        {
            var rollNumberParameter = rollNumber.HasValue ?
                new ObjectParameter("RollNumber", rollNumber) :
                new ObjectParameter("RollNumber", typeof(int));
    
            var paymentMonthParameter = paymentMonth != null ?
                new ObjectParameter("PaymentMonth", paymentMonth) :
                new ObjectParameter("PaymentMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentReport_Result>("GetPaymentReport", rollNumberParameter, paymentMonthParameter);
        }
    }
}
