//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byatikram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetPaymentReport_Result> GetPaymentReport(Nullable<int> rollNumber, string paymentMonth)
        {
            var rollNumberParameter = rollNumber.HasValue ?
                new ObjectParameter("RollNumber", rollNumber) :
                new ObjectParameter("RollNumber", typeof(int));
    
            var paymentMonthParameter = paymentMonth != null ?
                new ObjectParameter("PaymentMonth", paymentMonth) :
                new ObjectParameter("PaymentMonth", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentReport_Result>("GetPaymentReport", rollNumberParameter, paymentMonthParameter);
        }
    
        public virtual ObjectResult<GetPaymentReportWithType_Result> GetPaymentReportWithType(Nullable<int> rollNumber, string paymentMonth, string paymentType)
        {
            var rollNumberParameter = rollNumber.HasValue ?
                new ObjectParameter("RollNumber", rollNumber) :
                new ObjectParameter("RollNumber", typeof(int));
    
            var paymentMonthParameter = paymentMonth != null ?
                new ObjectParameter("PaymentMonth", paymentMonth) :
                new ObjectParameter("PaymentMonth", typeof(string));
    
            var paymentTypeParameter = paymentType != null ?
                new ObjectParameter("PaymentType", paymentType) :
                new ObjectParameter("PaymentType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaymentReportWithType_Result>("GetPaymentReportWithType", rollNumberParameter, paymentMonthParameter, paymentTypeParameter);
        }
    }
}
