//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byatikram
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDue
    {
        public int DueID { get; set; }
        public Nullable<int> RollNumber { get; set; }
        public Nullable<int> TotalDue { get; set; }
    }
}
