//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Byatikram
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentRollNumber { get; set; }
        public string GuardiansName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string School { get; set; }
        public string Class { get; set; }
        public Nullable<int> AdmissionFee { get; set; }
        public string MobileNumber { get; set; }
        public string Version { get; set; }
        public string Course { get; set; }
        public string MonthlyFee { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
